services:
  rust-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ayano-lab-unity-rust-games
    working_dir: /workspace/app
    command: ["./target/debug/rust-sandbox"]
    ports:
      - "18091:3000"
    volumes:
      - ./app:/workspace/app
    environment:
      - VIRTUAL_HOST=unity-rust-games.wos.ktsys.jp
      - VIRTUAL_PORT=3000
      - CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
    networks:
      - default
      - wos-proxy-network

networks:
  wos-proxy-network:
    external: true
